# TEM detector library with their specifications, can be extended
DETECTOR_LIBRARY = {   
    'Gatan 80X Metro': {   'aliases': ['80x.*metro', '80x.*metr', 'metro'],
                           'binning': 1,
                           'description': 'Gatan 80X Metro direct electron '
                                          'detector',
                           'image_height': 2048,
                           'image_width': 2048,
                           'pixel_size': 5},
    'K2 IS': {   'aliases': ['k2'],
                 'binning': 1,
                 'description': 'Gatan K2 IS direct electron detector',
                 'image_height': 3712,
                 'image_width': 3840,
                 'pixel_size': 5.0},
    'OneView': {   'aliases': ['oneview'],
                   'binning': 1,
                   'description': 'Gatan OneView sCMOS camera',
                   'image_height': 4096,
                   'image_width': 4096,
                   'pixel_size': 15},
    'Orius SC200D': {   'aliases': ['orius', 'sc200d'],
                        'binning': 1,
                        'description': 'Gatan Orius SC200D CCD camera',
                        'image_height': 2048,
                        'image_width': 2048,
                        'pixel_size': 7.4},
    'Ultrascan': {   'aliases': ['ultrascan'],
                     'binning': 1,
                     'description': 'Gatan Ultrascan CCD camera',
                     'image_height': 2048,
                     'image_width': 2048,
                     'pixel_size': 14.0}}
